"""empty message

Revision ID: 043251f1cf71
Revises: 2354ea7cdceb
Create Date: 2016-04-29 22:19:28.150881

"""

# revision identifiers, used by Alembic.
revision = '043251f1cf71'
down_revision = '2354ea7cdceb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('hashed', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'hashed')
    ### end Alembic commands ###
