"""empty message

Revision ID: 0f814b1a6c3c
Revises: None
Create Date: 2016-03-20 20:01:24.739637

"""

# revision identifiers, used by Alembic.
revision = '0f814b1a6c3c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=2), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myprofile')
    ### end Alembic commands ###
