"""empty message

Revision ID: 1d23658feff3
Revises: a0fef5fdd456
Create Date: 2016-03-21 15:10:24.857081

"""

# revision identifiers, used by Alembic.
revision = '1d23658feff3'
down_revision = 'a0fef5fdd456'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mywish',
    sa.Column('wishid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('description_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['myprofile.userid'], ),
    sa.PrimaryKeyConstraint('wishid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mywish')
    ### end Alembic commands ###
