"""empty message

Revision ID: 2354ea7cdceb
Revises: dd48de25365c
Create Date: 2016-04-21 03:28:39.307385

"""

# revision identifiers, used by Alembic.
revision = '2354ea7cdceb'
down_revision = 'dd48de25365c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mywish',
    sa.Column('wishid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('description_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['myprofile.userid'], ),
    sa.PrimaryKeyConstraint('wishid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mywish')
    ### end Alembic commands ###
