"""empty message

Revision ID: a0fef5fdd456
Revises: acd534e565ee
Create Date: 2016-03-21 02:23:06.079376

"""

# revision identifiers, used by Alembic.
revision = 'a0fef5fdd456'
down_revision = 'acd534e565ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mywish',
    sa.Column('wishid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('description_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('wishid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mywish')
    ### end Alembic commands ###
